// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NestedForm from "./nested_form"
import PrimaryPictureUpload from './primary_picture_upload_controller'
import GalleryPicturesUpload from './gallery_pictures_upload_controller'

import SortableList from './sortable_list'
import Flash from './flash_controller'
import Search from './search_controller'

// noinspection JSCheckFunctionSignatures
application.register("nested-form", NestedForm)
application.register("primary-picture-upload", PrimaryPictureUpload)
application.register("gallery-pictures-upload", GalleryPicturesUpload)
// noinspection JSCheckFunctionSignatures
application.register("sortable-list", SortableList)
application.register("flash", Flash)
application.register("search", Search)
